//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;




public class PermissionEnum
{
    
    public const string ViewRoleList = "View Role List";
    
    public const string ViewRoleDetail = "View Role Detail";
    
    public const string CreateRole = "Create Role";
    
    public const string UpdateRole = "Update Role";
    
    public const string DeleteRole = "Delete Role";
    
    public const string ViewRolePermission = "View Role Permission";
    
    public const string UpdateRolePermission = "Update Role Permission";
    
    public const string ViewUserList = "View User List";
    
    public const string ViewUserDetail = "View User Detail";
    
    public const string CreateUser = "Create User";
    
    public const string UpdateUser = "Update User";
    
    public const string DeleteUser = "Delete User";
    
    public const string ViewProductList = "View Product List";
    
    public const string ViewProductDetail = "View Product Detail";
    
    public const string CreateProduct = "Create Product";
    
    public const string UpdateProduct = "Update Product";
    
    public const string DeleteProduct = "Delete Product";
}
