//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppClient
    {
        public int ID { get; set; }
        public string AppName { get; set; }
        public string AppID { get; set; }
        public string AppSecret { get; set; }
        public string CallBackUrl { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
