//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActionEndPoint
    {
        public int EndPointID { get; set; }
        public int PermissionActionID { get; set; }
        public string APIController { get; set; }
        public string APIName { get; set; }
    
        public virtual tblPermissionActionJunc tblPermissionActionJunc { get; set; }
    }
}
