//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblModule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblModule()
        {
            this.tblPages = new HashSet<tblPage>();
        }
    
        public int ModuleID { get; set; }
        public string ModuleName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ModuleOrder { get; set; }
        public string ModuleIcon { get; set; }
        public Nullable<int> ParentID { get; set; }
        public bool IsChargeable { get; set; }
        public Nullable<decimal> Charges { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPage> tblPages { get; set; }
    }
}
