//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPermission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPermission()
        {
            this.tblPermissionActionJuncs = new HashSet<tblPermissionActionJunc>();
            this.tblRolePermissionJuncs = new HashSet<tblRolePermissionJunc>();
        }
    
        public int PermissionID { get; set; }
        public int PageID { get; set; }
        public string Permission { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tblPage tblPage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPermissionActionJunc> tblPermissionActionJuncs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRolePermissionJunc> tblRolePermissionJuncs { get; set; }
    }
}
