//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPermissionActionJunc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPermissionActionJunc()
        {
            this.tblActionEndPoints = new HashSet<tblActionEndPoint>();
        }
    
        public int PermissionActionID { get; set; }
        public int PermissionID { get; set; }
        public string Action { get; set; }
        public Nullable<int> IsLandingAction { get; set; }
    
        public virtual tblPermission tblPermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActionEndPoint> tblActionEndPoints { get; set; }
    }
}
